export const GET_LIST_PRODUCT_FAILURE = 'GET_LIST_PRODUCT_FAILURE';
export const GET_LIST_PRODUCT_REQUEST = 'GET_LIST_PRODUCT_REQUEST';

export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';

export const GET_FILTER_PRODUCT_FAILURE = 'GET_FILTER_PRODUCT_FAILURE';

export const GET_FILTER_PRODUCT_REQUEST = 'GET_FILTER_PRODUCT_REQUEST';
export const GET_FILTER_PRODUCT_SUCCESS = 'GET_FILTER_PRODUCT_SUCCESS';

export const GET_DETAIL_PRODUCT_FAILURE = 'GET_DETAIL_PRODUCT_FAILURE';
export const GET_DETAIL_PRODUCT_REQUEST = 'GET_DETAIL_PRODUCT_REQUEST';
export const GET_DETAIL_PRODUCT_SUCCESS = 'GET_DETAIL_PRODUCT_SUCCESS';

export const ADD_NEW_PRODUCT_FAILURE = 'ADD_NEW_PRODUCT_FAILURE';
export const ADD_NEW_PRODUCT_REQUEST = 'ADD_NEW_PRODUCT_REQUEST';
export const ADD_NEW_PRODUCT_SUCCESS = 'ADD_NEW_PRODUCT_SUCCESS';

export const FILTER_PRODUCT_BY_NAME = 'FILTER_PRODUCT_BY_NAME';
