export const GET_LIST_PRODUCT_FAILURE = 'GET_LIST_PRODUCT_FAILURE';
export const GET_LIST_PRODUCT_REQUEST = 'GET_LIST_PRODUCT_REQUEST';

export const GET_LIST_PRODUCT_SUCCESS = 'GET_LIST_PRODUCT_SUCCESS';
